//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTransaction
    {
        public int transactionNo { get; set; }
        public string loanAcid { get; set; }
        public Nullable<System.DateTime> EmiDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Outstanding { get; set; }
    
        public virtual LoanAccount LoanAccount { get; set; }
    }
}
