//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanAccount()
        {
            this.LoanTransactions = new HashSet<LoanTransaction>();
        }
    
        public string LoanAcid { get; set; }
        public string Custid { get; set; }
        public Nullable<int> LoanAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<double> LnRoi { get; set; }
        public Nullable<double> Emi { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanTransaction> LoanTransactions { get; set; }
    }
}
